baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mi portafolio LEDEZMA'

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[menu]
[[menu.main]]
  identifier="contactos"
  name="Contacto"
  title="contacto"
  url = "/contactos/"
  weight=0
[[menu.main]]
  identifier="contacto"
  name="Contacto"
  title="redes"
  url = "/contactos/"
  weight=0
[[menu.main]]
  identifier="post"
  name="post"
  title="COMENTARIOS"
  url = "/post/"
  weight=0
